import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Terra Firma Partners™",
  description:
    "Terms of Service for Terra Firma Partners LLC governing access to and use of the Terra Firma website, software, products, and services.",
};

function Clause({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <p className="text-stone-600">
      <strong className="text-stone-800">
        {id} {title}.
      </strong>{" "}
      {children}
    </p>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-stone-50 pt-20 pb-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-stone-800 mb-2">Terms of Service</h1>
        <p className="text-stone-500 mb-8">Last Updated: June 29, 2026</p>

        <div className="prose prose-stone max-w-none space-y-4">
          <p className="text-stone-600">Welcome to Terra Firma!</p>
          <p className="text-stone-600">
            Terra Firma Partners LLC (&ldquo;<strong>Terra Firma</strong>&rdquo;,{" "}
            &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo;) makes
            available for your use the Terra Firma website and its proprietary
            software, products, services, and any updates to the foregoing
            (collectively, the &ldquo;<strong>Service</strong>&rdquo; or &ldquo;
            <strong>Services</strong>&rdquo;) that Terra Firma provides subject to the
            terms and conditions herein and any additional terms contained in an
            amendment or addendum (collectively, these &ldquo;<strong>Terms</strong>
            &rdquo;). These Terms are between Terra Firma and the individual that
            accesses and/or uses the Services (&ldquo;<strong>you</strong>&rdquo;) and
            are effective as of the date you click &ldquo;I Accept&rdquo; or a similar
            electronic consent (the &ldquo;<strong>Effective Date</strong>&rdquo;). By
            accessing and using the Services, you agree to all of the terms outlined
            herein. The disclaimers, terms, and conditions in these Terms are of
            general application and may be supplemented by additional policies and
            procedures of specific application that Terra Firma may disclose from time
            to time.
          </p>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            1. Our Service
          </h2>
          <Clause id="1.1" title="Grant of Access">
            On the condition you pay all Fees and otherwise comply with your
            obligations under these Terms, and subject further to additional terms of
            Third-Party Products (as defined herein) made available to you in
            connection with the Service, Terra Firma hereby grants to you a limited,
            revocable, non-exclusive, non-transferable (except as provided in Section
            9.6) right to access and use the Services set forth under one or more
            service plans (each, a &ldquo;<strong>Service Plan</strong>&rdquo;) entered
            into by and between you and Terra Firma, along with related Documentation
            (as defined herein), solely in connection with your personal or internal
            business purposes. The foregoing right to access includes the non-exclusive
            right for you to use any outputs, reports, or other materials generated by
            the Service subject to these Terms. Other than as expressly granted in
            these Terms, no other rights or licenses to Terra Firma Materials (as
            defined herein) are granted. If you do not comply with these Terms, Terra
            Firma reserves the right to revoke, suspend, or limit your right to access
            and use the Service. Any use of the Service that exceeds the rights
            expressly granted in these Terms is strictly prohibited and constitutes a
            violation of these Terms, which may result in the suspension or termination
            of your right to access and use the Service. As used in these Terms,
            &ldquo;<strong>Documentation</strong>&rdquo; means any documentation made
            available by Terra Firma pertaining to the Service including, as
            applicable, any accompanying or online user guides or technical
            information relating to the Service, in each case, as may be updated or
            amended by or on behalf of Terra Firma from time to time.
          </Clause>
          <Clause id="1.2" title="Modification">
            You agree that Terra Firma has the right to change, modify, add to, or
            discontinue any aspect or feature of the Service at any time with or
            without notice. From time to time, Terra Firma may, but is under no
            obligation to, release upgrades, fixes, or new versions of the Service,
            although these releases may not be consistent across all platforms and
            devices.
          </Clause>
          <Clause id="1.3" title="Removal of Access">
            Terra Firma reserves the right to suspend, terminate, or refuse access to
            the Service for you in the event that: (i) you breach or violate, or are
            reasonably likely to breach or violate in Terra Firma&rsquo;s sole
            discretion, these Terms or other incorporated agreements, addenda, or
            guidelines; (ii) Terra Firma discontinues the applicable Service; (iii)
            there is a technical or security issue or problem; or (iv) you engage in
            fraudulent or illegal activities or a material breach of your obligations
            under these Terms. You further agree that such measures may be taken in
            Terra Firma&rsquo;s sole discretion and without any liability to you or any
            third party.
          </Clause>
          <Clause id="1.4" title="Defects and Availability">
            While Terra Firma uses commercially reasonable efforts to maintain and
            provide the Service, the Service is not a replacement for a land survey or
            title verification performed by a professional in the applicable field. By
            using the Service, you agree that Terra Firma is not responsible for any
            defects or failures associated with the Service or any damages (either
            direct or indirect) that may result from any such defects or failures.
            Terra Firma is not obligated to provide you support for, and shall not be
            responsible or liable for, any errors in the Service or any damages
            resulting from your failure to properly implement the Service on your
            network in accordance with the Documentation. The Service and any component
            thereof may be inaccessible or inoperable for any reason including, without
            limitation: (i) equipment malfunctions; (ii) periodic maintenance
            procedures or repairs which may be undertaken from time to time by Terra
            Firma or its third-party service providers; or (iii) any other causes
            beyond Terra Firma&rsquo;s reasonable control. Terra Firma does not make
            any guarantees regarding the reliability or availability of the Service and
            will not be liable to you or any third party for damages or losses related
            to the Service being unavailable or providing inaccurate outputs.
          </Clause>
          <Clause id="1.5" title="Third Party Products">
            The Service may permit use or permit access to Third-Party Products.
            &ldquo;<strong>Third-Party Products</strong>&rdquo; means any products,
            content, services, information, websites, or other materials that are
            provided or made available by third parties and are incorporated into or
            accessible through the Services. Third-Party Products are subject to their
            own terms and conditions presented to you for acceptance within the Service
            by website link or otherwise. If you do not agree to abide by the
            applicable terms for any such Third-Party Products, then you should not
            install, access, connect to, integrate, or use such Third-Party Products.
            Upon requesting to connect with Third-Party Products through the Service,
            the Service may transmit your information and request to applicable
            third-party providers via an application programming interface or similar
            technical integration to facilitate the connection with Third-Party
            Products. Your use of the Service to connect to Third-Party Products
            constitutes your consent for Terra Firma to transmit your data and service
            requests through the relevant interface or integration as necessary to
            facilitate your request. You further acknowledge and agree that Terra Firma
            will not be responsible or liable, directly or indirectly, and you hold
            Terra Firma harmless for any damage or loss caused by your use of or
            reliance upon any such Third-Party Products.
          </Clause>
          <Clause id="1.6" title="Ownership of Intellectual Property">
            As between you and Terra Firma, all images, trademarks, service marks,
            logos, and icons displayed on the Service, or the Terra Firma website, are
            the property of Terra Firma. All Terra Firma patents, copyrights, moral
            rights, trade secrets, trademarks, service marks, publicity rights, and
            other proprietary rights (collectively, &ldquo;
            <strong>Intellectual Property Rights</strong>&rdquo;) and all systems,
            databases, information, data, documents, materials, and works which are
            provided, used, or made available in connection with the Service
            (collectively, the &ldquo;<strong>Terra Firma Materials</strong>&rdquo;)
            shall be and remain at all times the property of Terra Firma and its
            third-party licensors. You are not acquiring any Intellectual Property
            Rights in or to the Terra Firma Materials other than a non-exclusive right
            to access and use the Service solely in accordance with these Terms. The
            Terra Firma Materials may not be reproduced, recreated, sublicensed,
            modified, accessed, or used in any manner or disseminated or distributed to
            any other party in violation of these Terms.
          </Clause>
          <Clause id="1.7" title="AI Technology">
            In the course of providing the Service, Terra Firma may utilize deep
            learning, machine learning, large language models, generative, and other
            proprietary artificial intelligence available to Terra Firma (collectively,
            &ldquo;<strong>AI Technology</strong>&rdquo;) to assist in the performance
            of the Service and output production therefrom. You acknowledge and agree
            that AI Technology is utilized to help provide the Service and that any
            outputs generated by AI Technology are generated based on your input and
            data available to the AI Technology and may not always be accurate,
            complete, or current. You agree that outputs and information generated by
            the Service, which may be the result of or informed by AI Technology
            functions, are not substitutes for decisions requiring professional
            judgment or factual verification and you are responsible for any actions or
            decisions you take based on such information. Where the AI Technology is
            hosted, operated, or powered in whole or in part by a third-party platform
            or provider, you acknowledge and consent by using the Service that your
            interactions, queries, and related data may be transmitted to and processed
            by the third-party platform or provider in accordance with its privacy
            notice or other similar policy. Terra Firma does not control and is not
            responsible for the functionality, operation, or performance of any
            third-party-provided AI Technology. Terra Firma makes no warranties of any
            kind, whether express or implied, including but not limited to warranties
            of accuracy, reliability, merchantability, or fitness for a particular
            purpose in relation to the AI Technology. Terra Firma makes no
            representation that the AI Technology will resolve any technical issue,
            provide correct information, or perform without interruption or error, and
            to the fullest extent permitted by law, Terra Firma disclaims all liability
            for any losses, damages, or harms arising out of or related to your
            reliance on or use of the AI Technology or its outputs.
          </Clause>
          <Clause id="1.8" title="Land Access">
            Certain features of the Services may allow you to identify, communicate
            with, or connect with other persons for the purpose of discussing
            potential access, use, lease, license, or other arrangements regarding
            land parcels. Any agreement, arrangement, understanding, or transaction
            entered into between you and any other person in connection with such
            features is solely between you and such person. Terra Firma is not a party
            to, and does not control, endorse, guarantee, or assume responsibility
            for, any separate agreement or relationship between you and any other
            person. You are solely responsible for negotiating, reviewing, entering
            into, and complying with any such separate agreement with such other person
            or persons. The availability of any connection, listing, or other feature
            accessible through the Service does not create any hunting right, access
            right, leasehold interest, license, agency relationship, partnership, joint
            venture, employment relationship, or other legal relationship between you,
            another person, or with Terra Firma. Terra Firma is not responsible for
            your acts or omissions, or your compliance with a separate agreement, or
            any injury, loss, damage, dispute, claim, or liability arising out of or
            relating to any land access, land use, or separate agreement between you and
            any other person. On behalf of yourself and on behalf of your heirs,
            successors, assigns, and permittees, you hereby indemnify, defend, and hold
            Terra Firma harmless from and against any and all claims, allegations,
            investigations, administrative actions, private rights of action, and all
            damages, fines, fees, losses, penalties, and costs (including reasonable
            attorneys&rsquo; and special witness fees) arising from or related to: (i)
            your entry onto, presence on, or use of any land, property, premises, or
            location identified, accessed, or otherwise made available through or in
            connection with the Service, or allowance of any of the foregoing if you
            are the individual or entity making the applicable property available; (ii)
            personal injury, death, property damage, trespass, nuisance, or injury to
            you or any third party resulting from or alleged to result from your access
            and activity, or your allowance of such access and activity, on any land
            made available or identified through the Service; (iii) your breach of any
            agreement with another third party as described under this Section 1.8; or
            (iv) your use or possession of firearms, weapons, equipment, animals, or
            other such materials on land identified or made available through the
            Service.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            2. Payment
          </h2>
          <Clause id="2.1" title="Payment Terms">
            You are responsible for paying all fees, charges, and other amounts set
            forth in the Service Plan (the &ldquo;<strong>Fees</strong>&rdquo;),
            together with any applicable Taxes (as defined below). We reserve the right
            to modify the Fees upon notice to you. Such notice may be provided at any
            time by posting the changes to our website, to your Account, or via email.
            Modifications in Fees will be effective as of the start of the next Renewal
            Term (as defined herein) following such notice. Any payments more than
            thirty (30) days past due will bear a late payment charge of 1.5% interest
            per month or the highest amount permitted by law, whichever is less. You
            are responsible for your own costs and expenses related to using the
            Service such as charges for Internet access, third-party software licenses,
            or other data transmission fees.
          </Clause>
          <Clause id="2.2" title="Payment Method; Credit Card Authorization">
            You agree to always keep your payment information current during the Term
            and authorize Terra Firma to charge such payment method (including but not
            limited to credit card, debit card, wire transfer, and/or automated
            clearing house) provided by you all amounts due under the Service Plan. By
            submitting such information, you grant Terra Firma the right to provide such
            information to third parties, including but not limited to{" "}
            <a
              className="text-emerald-700 underline underline-offset-2 hover:text-emerald-800"
              href="https://stripe.com/legal/consumer"
              target="_blank"
              rel="noopener noreferrer"
            >
              Stripe
            </a>
            , and their successors, for purposes of providing and billing for the
            Services. Terra Firma bills customers in advance monthly or once a year for
            recurring annual plans. All amounts due shall be paid in US dollars. Terra
            Firma may invoice you electronically or by paper invoice. You must notify
            Terra Firma within thirty (30) days of receipt of the invoice of any
            billing errors thereon. If you do not notify Terra Firma within this time,
            Terra Firma will not be required to correct the error and/or adjust your
            amounts due, and you hereby waive any claim, allegation, or contention with
            respect to such invoice. Terra Firma may, but is under no obligation to,
            issue refunds for Fees paid for your Account in its sole discretion.
          </Clause>
          <Clause id="2.3" title="Taxes">
            Fees are exclusive of all invoicing and bank processing fees, taxes,
            levies, or duties imposed by taxing authorities, and you are responsible
            for payment of all such fees, taxes, levies, or duties, excluding only
            United States income (federal or state) taxes imposed on Terra Firma,
            including, by way of example and not limitation, import duties and fees,
            sales, use, transfer, excise, value-added, and gross receipts (&ldquo;
            <strong>Taxes</strong>&rdquo;). In the event you are required to withhold
            any portion of service fees due to payments to banks or taxing authorities,
            (i) you agree to do so and to indemnify Terra Firma from any liability
            resulting from your failure to make such withholdings, and (ii) Terra Firma
            reserves the right to adjust the pricing of the Service so that you are
            responsible for payment to Terra Firma of the full amount for the Service,
            net of any such withholdings, so that the net amounts received by Terra
            Firma after such withholdings are equal to what was invoiced.
          </Clause>
          <Clause id="2.4" title="Early Termination Fee">
            For monthly Service Plans, there is no early termination fee or refunds.
            For annual Service Plans billed monthly, you agree to pay three (3) times
            the monthly cost specified in such annual Service Plans in the event you
            terminate these Terms prior to the expiration or termination of the
            specified Subscription Term (as defined herein).
          </Clause>
          <Clause id="2.5" title="Suspension">
            If you fail to pay any undisputed Fees for the Service, and such Fees become
            overdue, we may, upon prior notice, and without limiting our other rights
            and remedies, suspend your access to the Service until such overdue amounts
            are paid in full.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            3. User Responsibilities
          </h2>
          <Clause id="3.1" title="Account Registration">
            Access to the Service will be managed by you through your individual
            account (an &ldquo;<strong>Account</strong>&rdquo;). In registering an
            Account for access to the Service, you will be required to provide certain
            requested information. We will ask you to create a password. Once Account
            registration information is submitted, Terra Firma will have the right to
            approve or reject the requested registration in Terra Firma&rsquo;s sole
            discretion. You are responsible for providing and maintaining truthful,
            accurate, complete, and current information in connection with your
            Account. You are responsible for maintaining the confidentiality of your
            username and password and you are fully responsible for all activities
            performed by you and any resulting events that occur under your Account.
          </Clause>
          <Clause id="3.2" title="Unauthorized Use and Information Changes">
            You must immediately notify Terra Firma if your registration information
            changes, or you learn of or have reason to suspect any unauthorized use of
            your Account or any other breach of security. You are responsible for all
            activities that occur under your Account, including any damages to Terra
            Firma, the Service, or any component thereof resulting from unauthorized
            access to your Account and Terra Firma will have no liability to you or any
            third party for damages or loss related to such unauthorized access or use.
          </Clause>
          <Clause id="3.3" title="Representations">
            You hereby represent and warrant that: (i) you have the legal capacity and
            authority to enter into and perform your obligations under these Terms; (ii)
            you will comply with the terms and conditions of these Terms and any other
            agreement to which you are subject that is related to your use of the
            Service or any part thereof; (iii) you have provided and will maintain
            accurate and complete information, including, without limitation, your legal
            name, email address, and any other information Terra Firma may reasonably
            require; (iv) your access to and use of the Service or any part thereof will
            not constitute a breach or violation of any other agreement, contract,
            terms of use, or any law or regulation to which you are subject; and (v) you
            will not use the Service in order to gain competitive intelligence about
            Terra Firma, the Service, or any product or service offered via the Service
            or to otherwise compete with Terra Firma.
          </Clause>
          <Clause id="3.4" title="Restrictions">
            You may not: (i) license, sublicense, sell, resell, transfer, assign,
            distribute, or otherwise commercially exploit or make available to any
            third party any portion of our Service in any way; (ii) copy, modify,
            adapt, alter, translate, create derivative works, reverse engineer,
            decompile, disassemble, or otherwise attempt to learn the source code,
            communications protocol, structure, or ideas upon which the Service is
            based; (iii) use the Service or any data, content, or information accessed
            through the Service to develop a competing service or product; (iv) use any
            device, software, or routine intended to damage or otherwise interfere with
            the proper functioning of the Service, servers, data centers, or networks
            connected to the Service or take any other action that interferes with any
            other person&rsquo;s use of the Service; (v) decrypt, transfer, create
            Internet links to the Service, or &ldquo;frame&rdquo; or &ldquo;mirror&rdquo;
            the Service on any other server or wireless or Internet-based device; (vi)
            use or merge the Service or any component thereof with other software,
            databases, or services not provided or approved by Terra Firma; (vii)
            circumvent or attempt to circumvent any electronic protection measures in
            place to regulate or control access to the Service, or remove, obscure, or
            alter any notices or indications of any Intellectual Property Rights, any
            trade names, trademarks, service marks, logos, trade dress, and any other
            distinctive or proprietary symbols, labels, designs, or designations, or
            any electronic notices; (viii) use the Service for any fraudulent or
            otherwise unlawful purposes or in violation of these Terms; (ix) develop,
            distribute, or sell any software or other functionality capable of
            launching, being launched from, or otherwise integrated with the Service;
            (x) use any bot, spider, or other automatic or manual device or process for
            the purpose of harvesting or compiling information on the Service for any
            reason; (xi) access or attempt to access any other user&rsquo;s Account or
            use the Service in a way that prevents or inhibits another user from
            enjoying the Service; (xii) use any data, content, or information made
            available through the Service in any manner that misappropriates any trade
            secret or infringes any copyright, trademark, patent, rights of publicity,
            or other proprietary right of any party; (xiii) introduce into the Service
            any virus, rogue program, Trojan horse, worm, or other malicious or
            intentionally destructive code, software routines, or equipment components
            designed to permit unauthorized access to or disable, erase, or otherwise
            harm the Service, or perform any such actions; (xiv) introduce into the
            Service any back door, time bomb, drop dead device, or other software
            routine designed to disable a computer program automatically with the
            passage of time or under the positive control of an unauthorized person;
            (xv) delete, modify, hack, or attempt to change or alter the Service, any
            data, content, or information made available through the Service, or any
            notices on the Service; (xvi) connect to or access any Terra Firma computer
            system or network other than the Service; (xvii) impersonate any other
            person or entity to use or gain access to the Service; or (xviii) conduct or
            otherwise participate in any distributed denial-of-service attack or similar
            malicious attack intended or designed to artificially delay, disrupt, or
            otherwise adversely affect the Service or any other user&rsquo;s access to
            or use of the Service. Terra Firma reserves the right to fully investigate
            and prosecute violations of any of the above. Terra Firma may involve and
            cooperate with law enforcement authorities in prosecuting users who violate
            these Terms.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            4. Data Rights, Uses, and Limitations
          </h2>
          <Clause id="4.1" title="User Content">
            As part of your use of the Service, you may submit or upload data,
            information, materials, comments, prompts, and other content (&ldquo;
            <strong>User Content</strong>&rdquo;). User Content does not include Terra
            Firma&rsquo;s Usage Data (as defined herein). You hereby grant Terra Firma
            and its affiliates a non-exclusive, perpetual, irrevocable, royalty-free,
            fully paid, worldwide, sublicensable (through multiple tiers), fully
            transferable right and license during and after the Term to host, copy,
            process, transmit, display, perform, and otherwise use User Content to
            provide, maintain, support, enhance, and improve the Services. You shall
            have sole responsibility for the accuracy, quality, integrity, legality,
            reliability, appropriateness, and right to use such User Content. Terra
            Firma does not guarantee the security or availability of User Content and
            is not responsible for any loss or damage to User Content. You acknowledge
            and agree that you bear sole responsibility for adequately controlling,
            processing, storing, and backing up User Content. Terra Firma reserves the
            right, but not the obligation, to refuse to post or to remove any
            information or materials, in whole or in part, that Terra Firma believes to
            be unacceptable, undesirable, or in violation of these Terms or the rights
            of third parties.
          </Clause>
          <Clause id="4.2" title="User Content Representations">
            You represent, warrant, and covenant that you will not publish, post,
            upload, record, or otherwise distribute or transmit any User Content or
            other material that: (i) infringes or would infringe any copyright, patent,
            trademark, trade secret or other Intellectual Property Rights or
            proprietary right of any party, or any rights of publicity or privacy of
            any party; (ii) violates any law, statute, ordinance, or regulation; (iii)
            is inappropriate, profane, defamatory, libelous, obscene, indecent,
            threatening, harassing, or otherwise unlawful; (iv) is harmful to minors or
            otherwise pornographic; (v) is materially false, misleading, or inaccurate;
            and/or (vi) contains information for which you do not have the right to
            permit Terra Firma to access and process. You further represent and warrant
            that you have acquired all legally required consents, releases, and
            authorizations (freely given and fully informed) from all data subjects
            necessary to provide User Content to Terra Firma. You will indemnify,
            defend, and hold Terra Firma harmless from and against any and all claims,
            allegations, investigations, administrative actions, private rights of
            action, and all damages, fines, fees, losses, penalties, and costs
            (including reasonable attorneys&rsquo; and special witness fees), including
            those arising from or related to a claimed breach of state or federal data
            privacy or wiretapping laws caused by your failure to gain consent from
            applicable users for the use, monitoring of, or interaction with the
            Service for each instance in which the Service is or was deployed. The
            foregoing indemnification shall survive termination or expiration of these
            Terms.
          </Clause>
          <Clause id="4.3" title="Privacy">
            To the extent Terra Firma collects or acquires &ldquo;personal
            information&rdquo; as defined under applicable law in its performance of its
            obligations under these Terms, such collection shall be performed in
            accordance with its privacy policy linked here:{" "}
            <Link
              className="text-emerald-700 underline underline-offset-2 hover:text-emerald-800"
              href="/privacy"
            >
              Privacy Notice
            </Link>
            .
          </Clause>
          <Clause id="4.4" title="Usage Data and Aggregated Statistics">
            Terra Firma may generate de-identified data, statistics, and other
            performance or usage-related information (&ldquo;<strong>Usage Data</strong>
            &rdquo;) in the course of providing the Service to you. You acknowledge and
            agree that, as between you and Terra Firma, all Usage Data is and shall
            remain the property of Terra Firma. Terra Firma may use, aggregate, and
            share Usage Data for the purposes of providing the Service, conducting
            research, preparing industry benchmarking reports, product development, and
            other commercial uses subject to applicable law. Terra Firma will ensure
            that you cannot be identified through the Usage Data or any derivative
            thereof. You further acknowledge and agree that Terra Firma may compile
            Usage Data based on User Content input into the Services, provided such
            Usage Data does not identify you.
          </Clause>
          <Clause id="4.5" title="Feedback">
            Terra Firma welcomes comments, feedback, information, or materials
            regarding the Service or any of the other Terra Firma products or services
            (collectively, &ldquo;<strong>Feedback</strong>&rdquo;). By submitting
            Feedback to Terra Firma, you agree to assign, and hereby irrevocably assign
            to Terra Firma, all right, title, and interest, on a worldwide basis, in
            and to the Feedback and all copyrights, moral rights, and other
            Intellectual Property Rights embodied in such Feedback. Terra Firma will be
            free to use, copy, distribute, publish, and modify the Feedback on an
            unrestricted basis, without compensation to you.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            5. Term and Termination
          </h2>
          <Clause id="5.1" title="Term">
            These Terms commence on the Effective Date and continue until all Service
            Plans between you and Terra Firma have expired or been terminated in
            accordance with these Terms (the &ldquo;<strong>Term</strong>&rdquo;).
          </Clause>
          <Clause id="5.2" title="Terms of Service Plans">
            The term of each Service Plan shall be as specified when you order the
            applicable Service Plan (an &ldquo;<strong>Initial Subscription Term</strong>
            &rdquo;). Service Plans will automatically renew for additional periods
            equal to the expiring Initial Subscription Term or one year (whichever is
            shorter) (each, a &ldquo;<strong>Renewal Term</strong>&rdquo;, and
            collectively with the Initial Subscription Term, the &ldquo;
            <strong>Subscription Term</strong>&rdquo;), unless either party gives the
            other notice of non-renewal at least thirty (30) days before the end of the
            relevant Subscription Term.
          </Clause>
          <Clause id="5.3" title="Termination">
            Terra Firma may terminate these Terms for cause immediately if you breach
            these Terms, as determined by Terra Firma in its sole discretion, or become
            the subject of a lawsuit or any other proceeding relating to insolvency,
            liquidation, or assignment for the benefit of creditors. Either party may
            terminate these Terms for any reason with thirty (30) days&rsquo; written
            notice to the other party. Termination of these Terms shall not limit Terra
            Firma from pursuing remedies available to Terra Firma, including but not
            limited to injunctive relief, for a failure to pay outstanding Fees or in
            connection with any other breach of these Terms. You agree to cease use of
            the Services immediately upon the termination of these Terms.
          </Clause>
          <Clause id="5.4" title="Payment Upon Termination">
            If you terminate these Terms before the applicable Subscription Term
            expires, then you are not entitled to a refund or credit for any pre-paid
            Fees. You are responsible for any unpaid Fees for the Service for the
            entirety of the Term. You are also responsible for any Fees incurred prior
            to the date of termination.
          </Clause>
          <Clause id="5.5" title="Your Data Upon Termination">
            Your User Content associated with an applicable Service Plan will remain
            available for the duration of the Subscription Term and for thirty (30)
            days thereafter. For thirty (30) days after the Subscription Term ends, you
            may request a copy of your User Content and Terra Firma will provide such
            copy to you in a format reasonably available to Terra Firma. You agree that
            after termination or expiration of these Terms, or termination or
            expiration of any Service Plan, Terra Firma may immediately deactivate your
            Account(s) associated with the Service Plan, and you will no longer have
            access to such Account(s) after the Subscription Term has ended.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            6. Representations and Warranties
          </h2>
          <Clause id="6.1" title="Disclaimers">
            TERRA FIRMA MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE METHODOLOGIES
            USED OR THE ACCURACY, TIMELINESS, RELIABILITY OR COMPLETENESS OF ANY OF THE
            SERVICES. THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS
            AVAILABLE&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND WHATSOEVER, INCLUDING
            WITHOUT LIMITATION, ANY IMPLIED OR EXPRESS WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. THE SERVICES ARE NOT
            INTENDED TO PROVIDE YOU WITH ANY FINANCIAL, REAL ESTATE, OR RELATED ADVICE
            OF ANY KIND, AND TERRA FIRMA DOES NOT CLAIM TO BE, AND DOES NOT FUNCTION AS
            A SUBSTITUTE FOR, ANY PROFESSIONAL SURVEY OR TITLE VERIFICATION SERVICE.
            YOUR RELIANCE ON OR USE OF THE SERVICES SHALL BE ENTIRELY AT YOUR OWN RISK.
            TERRA FIRMA MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE LEGALITY OR
            PROPRIETY OF THE USE OF THE SERVICES IN ANY JURISDICTION, STATE OR REGION.
            YOU SHALL BE SOLELY RESPONSIBLE FOR OBTAINING ANY AND ALL NECESSARY
            LICENSES, CERTIFICATES, PERMITS, APPROVALS OR OTHER AUTHORIZATIONS REQUIRED
            BY FEDERAL, STATE OR LOCAL STATUTE, LAW OR REGULATION APPLICABLE TO YOUR USE
            OF THE SERVICES. THIS SECTION 6.1 APPLIES TO THE MAXIMUM EXTENT ALLOWED BY
            APPLICABLE LAW. THE SERVICES ARE OFFERED BY TERRA FIRMA FROM ITS FACILITIES
            IN THE UNITED STATES OF AMERICA. TERRA FIRMA MAKES NO REPRESENTATIONS THAT
            THE SERVICES ARE APPROPRIATE OR AVAILABLE FOR USE IN OTHER COUNTRIES. THOSE
            WHO ACCESS OR USE THE SERVICES FROM OTHER JURISDICTIONS DO SO AT THEIR OWN
            RISK AND ARE RESPONSIBLE FOR COMPLIANCE WITH ALL APPLICABLE LAWS.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            7. Limitation of Liability
          </h2>
          <Clause id="7.1" title="Liability">
            IN NO EVENT WILL TERRA FIRMA BE LIABLE FOR ANY INDIRECT, SPECIAL,
            INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING OUT OF OR
            RELATING TO THE SERVICES OR THESE TERMS, INCLUDING ANY LOSS OF DATA, LOST
            PROFITS, OR COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, HOWEVER
            CAUSED AND UNDER ANY THEORY OF LIABILITY, EVEN IF TERRA FIRMA HAS BEEN
            ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL TERRA
            FIRMA&rsquo;S AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS
            EXCEED THE TOTAL AMOUNTS PAID BY YOU TO TERRA FIRMA UNDER THE APPLICABLE
            SERVICE PLAN GIVING RISE TO THE CLAIM DURING THE TWELVE (12) MONTHS
            IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM. YOU ACKNOWLEDGE
            AND AGREE THAT TERRA FIRMA WILL NOT BE LIABLE FOR ANY CLAIMS OR DAMAGES
            ARISING FROM ANY ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SERVICES,
            ANY THIRD-PARTY PRODUCTS, MATERIALS, OR SERVICES, YOUR INTERACTIONS WITH
            OTHER USERS OR LANDOWNERS, YOUR ACTIONS, INACTIONS, OR EXPERIENCES ON ANY
            REAL ESTATE OR OTHER PROPERTY IDENTIFIED THROUGH THE SERVICES, OR YOUR USE
            OF, MISUSE OF, OR INABILITY TO USE THE SERVICES OR ANY THIRD-PARTY PRODUCTS,
            MATERIALS, OR SERVICES. YOU ACKNOWLEDGE AND AGREE THAT TERRA FIRMA WOULD NOT
            HAVE ENTERED INTO THESE TERMS BUT FOR THE LIMITATIONS OF LIABILITY SET FORTH
            IN THIS ARTICLE 7.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            8. Indemnification
          </h2>
          <Clause id="8.1" title="Your Indemnification">
            YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS TERRA FIRMA, ITS
            AFFILIATES AND RESPECTIVE OFFICERS, EMPLOYEES, CONSULTANTS, SHAREHOLDERS AND
            REPRESENTATIVES FROM AND AGAINST ANY AND ALL CLAIMS, LIABILITIES, DAMAGES,
            AND/OR COSTS (INCLUDING ATTORNEYS&rsquo; AND EXPERT WITNESS FEES, COSTS, AND
            OTHER EXPENSES) ARISING OUT OF OR RELATED TO ANY ACTUAL OR ALLEGED CLAIMS
            INVOLVING OR RESULTING FROM: (I) VIOLATION OF THESE TERMS OR APPLICABLE LAW,
            RULE OR REGULATION BY YOU OR ANY PERSON ACCESSING OR USING THE SERVICE BY OR
            THROUGH YOU; (II) INFRINGEMENT OR MISAPPROPRIATION BY YOU, OR ANY PERSON
            ACCESSING OR USING THE SERVICE BY OR THROUGH YOU, OF ANY INTELLECTUAL
            PROPERTY OR PRIVACY OR OTHER RIGHT OF ANY PERSON OR ENTITY (EXCEPT CLAIMS OF
            INFRINGEMENT OR MISAPPROPRIATION ARISING SOLELY FROM USE OF THE SERVICE AS
            PROVIDED UNDER THESE TERMS); (III) YOUR ACTS OR OMISSIONS; (IV) USER CONTENT
            IN ANY MANNER; OR (V) ANY NEGLIGENT ACT OR OMISSION OR WILLFUL MISCONDUCT BY
            YOU. TERRA FIRMA RESERVES THE RIGHT TO CONTROL THE DEFENSE AND ANY
            SETTLEMENT OF SUCH CLAIM, AND YOU SHALL COOPERATE WITH TERRA FIRMA IN
            DEFENDING AGAINST SUCH CLAIM.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            9. General Terms
          </h2>
          <Clause id="9.1" title="Independent Contractors">
            You understand and expressly agree that you and Terra Firma are independent
            contractors and not agents or employees of the other party. Neither you nor
            Terra Firma has any right, power, or authority to act or create any
            obligation, express or implied, on behalf of the other party.
          </Clause>
          <Clause id="9.2" title="Notices">
            Terra Firma may send notices pursuant to these Terms to the email address
            associated with your Account, and such notices will be deemed received one
            day after they are sent. You may send notices pursuant to these Terms to
            Terra Firma at{" "}
            <a
              className="text-emerald-700 underline underline-offset-2 hover:text-emerald-800"
              href="mailto:info@terrafirmapartners.com"
            >
              info@terrafirmapartners.com
            </a>
            , and such notices will be deemed received one day after they are sent.
          </Clause>
          <Clause id="9.3" title="Amendment">
            Terra Firma may amend these Terms (including any addenda referenced herein)
            from time to time by posting an amended version at its website and sending
            you written notice thereof. Such amendment will become effective as of the
            &ldquo;Last Updated&rdquo; legend at the top of the first page. Your
            continued use of the Service will constitute your agreement to any new
            provisions within the revised Terms. If you do not agree to the revised
            Terms, then you must stop using the Service immediately.
          </Clause>
          <Clause id="9.4" title="Force Majeure">
            Neither party shall be liable for failing or delaying performance of its
            obligations (except for the payment of money) resulting from any condition
            beyond its reasonable control, including but not limited to governmental
            action, acts of terrorism, natural disasters, earthquake, fire, flood, or
            other acts of God, labor conditions, power failures, and Internet
            disturbances (each, a &ldquo;<strong>Force Majeure Event</strong>&rdquo;).
            If a Force Majeure Event causes delays in performance by either party for a
            period longer than ninety (90) days, these Terms may be terminated in
            accordance with Section 5.3.
          </Clause>
          <Clause id="9.5" title="No Waiver">
            Neither party will be deemed to have waived any of its rights under these
            Terms by lapse of time or by any statement or representation other than (i)
            by an authorized representative and (ii) in an explicit written waiver. No
            waiver of a breach of these Terms will constitute a waiver of any prior or
            subsequent breach of these Terms.
          </Clause>
          <Clause id="9.6" title="Assignment and Successors">
            Neither party may assign these Terms or any of its rights or obligations
            hereunder without the other party&rsquo;s express written consent, except
            that either party may assign these Terms to the surviving party in a merger
            of that party into another entity following at least thirty (30) days&rsquo;
            prior written notice to the other party in advance of such merger. Except to
            the extent forbidden in the previous sentence, these Terms will be binding
            upon and inure to the benefit of the respective successors and assigns of
            the parties.
          </Clause>
          <Clause id="9.7" title="Choice of Law and Jurisdiction">
            These Terms will be governed solely by the laws of the state of Missouri.
            The parties hereby submit to the jurisdiction of, and waive any venue
            objections against, the state and federal courts located in Jackson County,
            Missouri, in any litigation arising out of or relating to these Terms or
            their subject matter. Before initiating any legal claim or action (except
            with respect to equitable relief or non-payment of fees due under these
            Terms), the parties will first attempt in good faith to resolve any dispute,
            controversy, or claim arising out of or related to these Terms
            (collectively, a &ldquo;<strong>Claim</strong>&rdquo;) through informal
            discussions. Either party may initiate this process by providing written
            notice describing the dispute in reasonable detail. The parties&rsquo;
            representatives shall meet in person or via conference call within ten (10)
            business days of such notice. If the parties have not reached a mutually
            agreeable resolution of the Claim within ten (10) business days after their
            initial meeting, or within an additional time period mutually agreed upon,
            then either party may request that such Claim be submitted to a mediator
            agreed upon by the parties who shall be recognized by the Association of
            Missouri Mediators, with such mediation to be held in Jackson County,
            Missouri, or in a separate location or virtually as mutually agreed by the
            parties. The mediator shall assist in attempting to negotiate a resolution
            of the Claim. The mediation shall be non-binding unless the parties
            otherwise agree. Unless otherwise agreed by the mediator and the parties,
            the mediation shall be held within twenty-one (21) days of the request for
            mediation. The parties must attend the mediation and act in good faith to
            genuinely attempt to resolve the Claim. Any information or documents
            disclosed by a party under this clause: (i) must be kept confidential; and
            (ii) may only be used to attempt to resolve the Claim. Each party shall pay
            its own costs of complying with this Section 9.7 and shall equally share the
            cost of the mediator. In the event the foregoing mediation does not resolve
            the Claim, either party may pursue all available remedies.
          </Clause>
          <Clause id="9.8" title="Equitable Relief">
            You agree that your breach of the terms and responsibilities under these
            Terms would cause irreparable harm and significant injury to Terra Firma,
            which would be both difficult to ascertain and for which there is no
            adequate remedy at law, and that Terra Firma shall be entitled, in addition
            to any other rights and remedies it may have, to injunctive relief (without
            the requirement of posting bond), specific performance, and other equitable
            remedies to restrain any threatened, continuing, or further breach, or
            other equitable relief without prejudice to any other rights and remedies
            Terra Firma may have under these Terms.
          </Clause>
          <Clause id="9.9" title="Severability">
            If any term or provision of these Terms is held to be invalid, illegal, or
            unenforceable, the remaining terms and provisions of these Terms will
            remain in full force and effect, and such invalid, illegal, or
            unenforceable term or provision will be deemed not to be part of these
            Terms.
          </Clause>
          <Clause id="9.10" title="Entire Agreement">
            These Terms, including any exhibits or addenda referenced herein, set forth
            the entire agreement of the parties and supersede all prior or
            contemporaneous writings, negotiations, and discussions with respect to the
            subject matter hereof. Neither party has relied upon any such prior or
            contemporaneous communications.
          </Clause>
          <Clause id="9.11" title="Survival">
            The following articles and sections will survive the expiration or
            termination of these Terms for any reason: Sections 1.6, 2.4, 3.4, 4.4,
            4.5, 5.4, and 5.5; Articles 6 through 9; and to the extent such sections
            discuss liability and any limitations thereof, Sections 1.7, 1.8, 4.1, and
            4.2.
          </Clause>

          <h2 className="text-xl font-semibold text-stone-800 mt-8 mb-3">
            Contact
          </h2>
          <p className="text-stone-600">
            For questions regarding these Terms of Service, please contact us at{" "}
            <a
              className="text-emerald-700 underline underline-offset-2 hover:text-emerald-800"
              href="mailto:info@terrafirmapartners.com"
            >
              info@terrafirmapartners.com
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
